version: '3'

services:
   sonarqube:
      image: sonarqube:8-community
      depends_on:
         - db
      environment:
         - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
         - sonar.jdbc.username=sonar
         - sonar.jdbc.password=sonar
      ulimits:
         nofile:
            soft: 65536
            hard: 65536
      volumes:
         - /tmp/opt/sonarqube/conf:/opt/sonarqube/conf \
         - /tmp/opt/sonarqube/logs:/opt/sonarqube/logs \
         - /tmp/opt/sonarqube/data:/opt/sonarqube/data \
         - /tmp/opt/sonarqube/extensions:/opt/sonarqube/extensions \
      ports:
         - "9000:9000"
         - "9092:9092"
   db:
      image: postgres:12
      environment:
         POSTGRES_USER: sonar
         POSTGRES_PASSWORD: sonar
         PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
         - ./sonar-data:/var/lib/postgresql/data
